# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            HELPER
tagline:          'A Jekyll theme'
description:      '✨Helpful 📬(article) or 🗂(document) or 📱(website)'
url:              https://helper.bin-e.com/
baseurl:          /

author:
  name:           'Bin-e'
  url:            https://github.com/bin-e

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bin-e/helper
